Adds bar login
anthonymesa/liquorish-backend pull request #45
Opened 2022-03-26 18:17 UTC by JakeKeels

2022-03-29 01:45 UTC, anthonymesa requested changes
Great job! only some minor changes!

2022-03-29 01:45 UTC, anthonymesa commented on routes/loginUser.js
> +            ) and password = '${password}' group by user_id
This update does not match the current names for the tables and table values in the database

2022-03-29 01:45 UTC, anthonymesa commented on routes/loginBar.js
> +  let user_id = null;
maybe this should be bar_id?

2022-03-30 23:01 UTC, JakeKeels commented
Fixes issues. Fixes issue #39.

2022-03-31 02:47 UTC, merged