add user saved drink route,
anthonymesa/liquorish-backend pull request #52
Opened 2022-03-29 02:53 UTC by JakeKeels

This requires review and further testing before being fully committed to the main branch.

2022-03-29 03:26 UTC, anthonymesa requested changes
really only minor changes!

2022-03-29 03:26 UTC, anthonymesa commented on routes/create/createSavedDrink.js
> +        console.log(update);
is 'update' an artifact from other code?

2022-03-29 03:26 UTC, anthonymesa commented on routes/create/createSavedDrink.js
> +            const request = new Request(update,
I see now, you should replace 'update' with sql_query.

2022-03-29 03:26 UTC, anthonymesa commented on routes/create/createSavedDrink.js
> +                        resolve(createResponse(0, rowCount == 1));
Will the updating of a table actually return any rows? If not, we can be fine to resolve null here given the status value is 0

2022-03-29 03:26 UTC, anthonymesa commented on routes/update/updateReadyStatus.js
> +          resolve(createResponse(0, rowCount == 1));
Again, if no rows are returned, we can just resolve with a value of null in the createResponse function

2022-03-29 03:26 UTC, anthonymesa commented on server.js
updateReadyStatus needs to be set to a route

2022-03-30 22:54 UTC, JakeKeels commented
Fixed the minor issues, should be ok to pull

2022-03-31 03:25 UTC, merged